/*-------------------------------------------------------------------------
   (C) Michael Finnegan        15 May 1999
-------------------------------------------------------------------------*/

//This inclue file includes all "main's" includes files
// necessary to build project Swift

#include "file.h"
#include "help.h"
#include "memory.h"
#include "labels.h"
#include "editor.h"
#include "print.h"
